# Generated by Django 4.2.6 on 2023-10-11 14:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date posted')),
                ('content', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), blank=True, size=None)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('display_name', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='')),
                ('bio', models.CharField(max_length=200)),
                ('posts', models.ManyToManyField(blank=True, related_name='posted', to='onlykiwis.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlykiwis.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='posted_on', to='onlykiwis.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlykiwis.user'),
        ),
    ]
