# Generated by Django 4.2.6 on 2023-10-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlykiwis', '0003_comment_date_user_date_alter_user_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
